# enter variables for easy prediction config
city_name = "Luxembourg_small"

# for green roofs, change to "Green"
target_type = "Green"


# optional settings
img_size = 256
checkpoint_path = "checkpoint"
solar_checkpoint = "solar_demo.pth"
green_checkpoint =  "Green-checkpoint-100-of-100.pth" #"green_demo.pth"